---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ${MOLECULE_DISTRO_NAME:-ubuntu-bionic}
    image: ${MOLECULE_DISTRO_IMAGE:-ubuntu:bionic}

provisioner:
  name: ansible
  playbooks:
    prepare: ../specific-version/converge.yml
    converge: converge.yml

verifier:
  name: ansible